In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


In [2]:
# load image path
import cv2 as cv
from keras.utils.image_utils import load_img,img_to_array
img_folder = Path("archive/flowers")

label = ["daisy","dandelion","rose",'sunflower']
test_image = list([])
X_data = np.empty((0,28*28))
Y_label = []

for i in range(len(label)):
    train_folder = img_folder/label[i]
    test = list(train_folder.glob("*.jpg"))
    test_image = test_image + test
    Y_label = Y_label+[i]*len(list(train_folder.glob("*.jpg")))

for  i in range(len(test_image)):
    image_path = str(test_image[i])
    img = load_img(image_path,target_size=(28,28),color_mode = "grayscale")
    img= img_to_array(img)
    img = img.astype("float32")/255
    

    img = np.reshape(img,(1,28*28))
    X_data = np.vstack((X_data,img))
print(X_data.dtype)

2022-11-01 11:20:20.491634: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-01 11:20:20.625133: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-01 11:20:21.098113: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tan/Carla_envi/Car_enviroment/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/lib64
2022-11-01 11:20:21.098155: W tensorflow/stream_executor/platform/default/dso_

float64


In [4]:
print(X_data)

[[0.60784316 0.6156863  0.60392159 ... 0.14509805 0.14901961 0.15294118]
 [0.16862746 0.2        0.23921569 ... 0.41960785 0.18431373 0.19215687]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.24705882 0.33725491 0.15294118 ... 0.21568628 0.20784314 0.33333334]
 [0.92941177 0.38039216 0.25490198 ... 0.14117648 0.78039217 0.35294119]
 [0.57254905 0.58431375 0.60392159 ... 0.53333336 0.50980395 0.48235294]]


In [5]:
print(Y_label)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [6]:
from keras.models import Sequential
from keras import layers

model = Sequential()
model.add(layers.Flatten(input_shape=[28*28]))
model.add(layers.Dense(600,activation="relu"))
model.add(layers.Dense(300,activation="relu"))
model.add(layers.Dense(100,activation="relu"))
model.add(layers.Dense(4,activation="softmax"))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 600)               471000    
                                                                 
 dense_1 (Dense)             (None, 300)               180300    
                                                                 
 dense_2 (Dense)             (None, 100)               30100     
                                                                 
 dense_3 (Dense)             (None, 4)                 404       
                                                                 
Total params: 681,804
Trainable params: 681,804
Non-trainable params: 0
_________________________________________________________________


2022-10-24 22:23:41.826808: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tan/Carla_envi/Car_enviroment/lib/python3.8/site-packages/cv2/../../lib64:
2022-10-24 22:23:41.826842: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-24 22:23:41.826873: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dauphongtantan): /proc/driver/nvidia/version does not exist
2022-10-24 22:23:41.827253: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
model.compile(optimizer= "rmsprop",loss = "categorical_crossentropy",metrics=["accuracy"])

In [8]:
from keras.utils import to_categorical
Y_label = to_categorical(Y_label)
print(Y_label)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [9]:
print(Y_label.shape)

(3333, 4)


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_data,Y_label,test_size=0.3,shuffle=True)

In [11]:
model.fit(X_train,Y_train,epochs =200,batch_size =128,validation_data=[X_test,Y_test])

Epoch 1/200
19/19 [==============================] - 1s 18ms/step - loss: 1.5918 - accuracy: 0.2975 - val_loss: 1.3483 - val_accuracy: 0.2580
Epoch 2/200
19/19 [==============================] - 0s 10ms/step - loss: 1.3629 - accuracy: 0.3168 - val_loss: 1.3875 - val_accuracy: 0.2910
Epoch 3/200
19/19 [==============================] - 0s 9ms/step - loss: 1.3271 - accuracy: 0.3395 - val_loss: 1.5367 - val_accuracy: 0.3320
Epoch 4/200
19/19 [==============================] - 0s 10ms/step - loss: 1.3350 - accuracy: 0.3463 - val_loss: 1.3198 - val_accuracy: 0.3410
Epoch 5/200
19/19 [==============================] - 0s 9ms/step - loss: 1.3153 - accuracy: 0.3558 - val_loss: 1.4329 - val_accuracy: 0.2540
Epoch 6/200
19/19 [==============================] - 0s 9ms/step - loss: 1.3030 - accuracy: 0.3686 - val_loss: 1.3399 - val_accuracy: 0.3600
Epoch 7/200
19/19 [==============================] - 0s 10ms/step - loss: 1.3144 - accuracy: 0.3811 - val_loss: 1.3840 - val_accuracy: 0.3610
Epoch 8/2