In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path



In [2]:
# load image path
import cv2 as cv
from keras.utils.image_utils import load_img,img_to_array
img_folder = Path("/home/tan/Documents/AI_thaythinh/homework/classAI/data/datak20/Data_AI_k20")

label = ["Ai","Tan","Thoai",'Thuong']
test_image = list([])
X_data = np.empty((0,32*32))
Y_label = []

for i in range(len(label)):
    train_folder = img_folder/label[i]
    
    test = list(train_folder.glob("*.jpg"))
    
    test_image = test_image + test
    Y_label = Y_label+[i]*len(list(train_folder.glob("*.jpg")))

for  i in range(len(test_image)):
    image_path = str(test_image[i])
    img = load_img(image_path,target_size=(32,32),color_mode = "grayscale")
    img= img_to_array(img)
    img = img.astype("float32")/255
   

    img = np.reshape(img,(1,32*32))
    X_data = np.vstack((X_data,img))
print(X_data.dtype)


2022-12-08 14:00:30.841232: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-08 14:00:30.958393: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tan/.local/lib/python3.8/site-packages/cv2/../../lib64:
2022-12-08 14:00:30.958407: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-08 14:00:30.978425: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been

float64


In [53]:
folder = Path("classAI/data/datak20/Data_AI_k20/Thoai")
print(list(folder.glob("*.jpg")))

[]


In [63]:
from keras.models import Sequential
from keras import layers

model = Sequential()
model.add(layers.Flatten(input_shape=[32*32]))
model.add(layers.Dense(512,activation="relu"))
model.add(layers.Dense(300,activation="relu"))
model.add(layers.Dense(100,activation="relu"))
model.add(layers.Dense(4,activation="softmax"))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 1024)              0         
                                                                 
 dense_12 (Dense)            (None, 512)               524800    
                                                                 
 dense_13 (Dense)            (None, 300)               153900    
                                                                 
 dense_14 (Dense)            (None, 100)               30100     
                                                                 
 dense_15 (Dense)            (None, 4)                 404       
                                                                 
Total params: 709,204
Trainable params: 709,204
Non-trainable params: 0
_________________________________________________________________


In [57]:
print(Y_label)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 

In [64]:
model.compile(optimizer= "rmsprop",loss = "categorical_crossentropy",metrics=["accuracy"])

In [65]:
from keras.utils import to_categorical
Y_label = to_categorical(Y_label)
print(Y_label)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_data,Y_label,test_size=0.3,shuffle=True)

In [67]:
model.fit(X_train,Y_train,epochs =200,batch_size =128,validation_data=[X_test,Y_test])

Epoch 1/200
2/2 [==============================] - 1s 255ms/step - loss: 2.7990 - accuracy: 0.1647 - val_loss: 5.2832 - val_accuracy: 0.2685
Epoch 2/200
2/2 [==============================] - 0s 21ms/step - loss: 5.2233 - accuracy: 0.2972 - val_loss: 1.4468 - val_accuracy: 0.3426
Epoch 3/200
2/2 [==============================] - 0s 22ms/step - loss: 1.9796 - accuracy: 0.3133 - val_loss: 1.7640 - val_accuracy: 0.2222
Epoch 4/200
2/2 [==============================] - 0s 21ms/step - loss: 1.3613 - accuracy: 0.5622 - val_loss: 0.9840 - val_accuracy: 0.7778
Epoch 5/200
2/2 [==============================] - 0s 23ms/step - loss: 0.9861 - accuracy: 0.6225 - val_loss: 1.3453 - val_accuracy: 0.4537
Epoch 6/200
2/2 [==============================] - 0s 22ms/step - loss: 1.2184 - accuracy: 0.4980 - val_loss: 0.7871 - val_accuracy: 0.8333
Epoch 7/200
2/2 [==============================] - 0s 23ms/step - loss: 0.6825 - accuracy: 0.8635 - val_loss: 0.6086 - val_accuracy: 0.9722
Epoch 8/200
2/2 [==